/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mtagab_security_Verification */

#ifndef _Included_me_mtagab_security_Verification
#define _Included_me_mtagab_security_Verification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mtagab_security_Verification
 * Method:    approvalcode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_mtagab_security_Verification_approvalcode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_mtagab_security_Verification
 * Method:    authenticated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_me_mtagab_security_Verification_authenticated
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
